### ISSUE TITLE
MEF Composition Error

### ISSUE THREAD

**Issue by Serphera** [DemonRem/RavenManager#1]
Hello, I'm getting this error whenever I try to either run your release or one built from the source.
Thought I'd give you a heads up.

![UPKTool](https://user-images.githubusercontent.com/33417890/55897448-d06a8100-5bc0-11e9-81df-1b795112665e.png)

**Comment by andreyka909** [comment]
Same for me, fix inc?

**Comment by DemonRem** [comment]
thank for letting me know I fix it today

**Comment by DemonRem** [comment]
@Serphera @andreyka909 
bug is fixed and the tool ready for use , enjoy.
